"""
mock_data.py
Provides mock candidates and classified rows derived from the real transcript
so the full pipeline can be tested without an OpenAI API key.

Run with: python src/main.py --input <transcript> --mode payload --mock
"""

MOCK_CANDIDATES = [
    {
        "candidate_title": "AI Comfort / General Use Policy Rollout",
        "candidate_summary": "Baker Youssef described sending a general AI comfort communication to the full Electronics group, addressing acceptable use, licensing tiers, and enablement gaps.",
        "source_speaker": "Baker, Youssef F",
        "source_timestamp": "5:54",
        "evidence_summary": "Youssef sent a general comfort or general use guidance on AI for the full electronics group, noting that enablement and access issues are a known problem for users not getting compiled license access.",
        "confidence": "High",
    },
    {
        "candidate_title": "Copilot Access & License Enablement Standard Work",
        "candidate_summary": "Multiple speakers discussed that users are not getting access to the right Copilot license tiers and that standard work for enablement is needed.",
        "source_speaker": "Gonzalez Medina, Oscar A",
        "source_timestamp": "12:55",
        "evidence_summary": "Oscar asked about users not getting access to the compiled license and whether enablement is a documented pain point. Jesse Horwitz added that users uncomfortable with command-line tools need a clearer onboarding path.",
        "confidence": "High",
    },
    {
        "candidate_title": "Command-Line / Technical Barrier Onboarding Guide",
        "candidate_summary": "Jesse Horwitz raised that users unfamiliar with command-line tools face a barrier to AI adoption and suggested this be addressed with guided onboarding.",
        "source_speaker": "Horwitz, Jesse",
        "source_timestamp": "16:20",
        "evidence_summary": "Jesse asked whether people uncomfortable using command line tools could hear about the tooling in a way that reduces friction. Suggests a non-technical onboarding path is needed.",
        "confidence": "Medium",
    },
    {
        "candidate_title": "Visual Installer Product Documentation Pipeline (AI-Assisted)",
        "candidate_summary": "David Hein demonstrated an AI-supported pipeline for generating Visual Installer product documentation, using agents to synthesize how-to guides from raw content.",
        "source_speaker": "Hein, David M",
        "source_timestamp": "19:12",
        "evidence_summary": "David M Hein presented a product manager workflow using AI agents to organize and synthesize documentation, coaching the output into how-to guide format for Visual Installer.",
        "confidence": "High",
    },
    {
        "candidate_title": "AI-Assisted Content Organization & Coaching Workflow",
        "candidate_summary": "David Hein described using an agent to coach and organize unstructured content into structured documentation, reducing manual writing effort.",
        "source_speaker": "Hein, David M",
        "source_timestamp": "33:07",
        "evidence_summary": "The agent has been helping David coach how to organize content into structured how-to guides, replacing a previously manual synthesis process.",
        "confidence": "High",
    },
    {
        "candidate_title": "Content Accessibility & Consumption Format Standard",
        "candidate_summary": "David Hein flagged that AI-generated content needs to be formatted for accessibility and downstream consumption, suggesting a next-step for content standards.",
        "source_speaker": "Hein, David M",
        "source_timestamp": "36:37",
        "evidence_summary": "David noted that content should be made accessible to consume and identified capturing accessibility format requirements as a next step.",
        "confidence": "Medium",
    },
    {
        "candidate_title": "Skills / Prompts Repository Maintenance Model",
        "candidate_summary": "Ryan Zaveruha and David Hein discussed maintaining a skills/prompts repository in Azure, including ownership and sustainment model as adoption grows.",
        "source_speaker": "Zaveruha, Ryan A",
        "source_timestamp": "40:35",
        "evidence_summary": "Ryan discussed maintaining a repo in Azure at a stable state. David agreed the skills repo should have a clear maintainer and sustainment model.",
        "confidence": "High",
    },
    {
        "candidate_title": "Knowledge Base Candidate Pipeline — Release Notes & VAS Standard Work",
        "candidate_summary": "David High confirmed two KB candidates are being moved through: Kenny's release notes documentation and VAS standard work for the AI knowledge base.",
        "source_speaker": "High, David K",
        "source_timestamp": "44:48",
        "evidence_summary": "David K High stated there are two knowledge base candidates in motion — release notes documentation and VAS standard work — being progressed through the KB pipeline.",
        "confidence": "High",
    },
]

MOCK_CLASSIFIED_ROWS = [
    {
        "Title": "AI Comfort / General Use Policy Rollout",
        "ProblemPainPoint": "No formal AI use policy or comfort guidance existed for the Electronics group, leaving employees uncertain about acceptable use, licensing, and tooling.",
        "RequestingTeam": "Cross Functional",
        "CurrentStatus": "(2) Needs Review",
        "Priority": "High",
        "OperatingBucket": "Crosss-Functional/Governance",
        "ProcessStage": "Governance/Intake",
        "UpstreamDownstreamImpact": "Cross-Functional",
        "AIUseCaseType": "Classification",
        "PrimaryFunctionChoice": "Organize",
        "LevelOfAnalysis": "Level 1 - Categorization",
        "HumanReviewRequired": True,
        "AutomationRisk": "Low - Read Only/Summarize Only",
        "SignalStrength": "Cross-Functional Pattern",
        "FrequencyOfPainPoint": "Continuous",
        "ManualEffortLevel": "Medium",
        "Repeatability": "High",
        "ScalabilityPotential": "Cross-Functional",
        "PrimaryTool": "Copilot",
        "PrimaryDataSource": "Meeting Transcript",
        "IntegrationNeeded": False,
        "DataSensitivity": "Internal",
        "GuardrailsNeeded": "Policy must be reviewed by legal/HR before distribution. AI use guidance should not conflict with IT security standards.",
        "SecurityAccessConcern": False,
        "LegalComplianceConcern": True,
        "HumanInTheLoopRequired": True,
        "NextStep": "Finalize and distribute AI comfort/policy document to Electronics group. Schedule follow-up to capture questions.",
        "ScheduleHealth": "Not Started",
        "ValueScore": 4,
        "EffortScore": 2,
        "RiskScore": 2,
        "ReadinessScore": 3,
        "SignalScore": 4,
        "SuggestedBusinessOwnerText": "Baker, Youssef F",
        "SuggestedTechnicalOwnerText": "",
        "SuggestedSMEChampionText": "Baker, Youssef F",
        "EvidenceSummary": "Youssef sent a general comfort or general use guidance on AI for the full electronics group.",
        "SourceSpeaker": "Baker, Youssef F",
        "SourceTimestamp": "5:54",
        "ConfidenceLevel": "High",
    },
    {
        "Title": "Copilot Access & License Enablement Standard Work",
        "ProblemPainPoint": "Users are not getting access to the correct Copilot license tiers. Enablement gaps exist and there is no standard work to resolve them consistently.",
        "RequestingTeam": "Cross Functional",
        "CurrentStatus": "(2) Needs Review",
        "Priority": "High",
        "OperatingBucket": "Crosss-Functional/Governance",
        "ProcessStage": "Governance/Intake",
        "UpstreamDownstreamImpact": "Cross-Functional",
        "AIUseCaseType": "Both",
        "PrimaryFunctionChoice": "Organize",
        "LevelOfAnalysis": "Level 2 - Descriptive Analysis",
        "HumanReviewRequired": True,
        "AutomationRisk": "Medium - Recommendations with human review",
        "SignalStrength": "Repeated Across Multiple Teams",
        "FrequencyOfPainPoint": "Continuous",
        "ManualEffortLevel": "High",
        "Repeatability": "High",
        "ScalabilityPotential": "Cross-Functional",
        "PrimaryTool": "Copilot",
        "PrimaryDataSource": "Meeting Transcript",
        "IntegrationNeeded": True,
        "DataSensitivity": "Internal",
        "GuardrailsNeeded": "License provisioning must go through IT. Standard work should not bypass IT access controls.",
        "SecurityAccessConcern": True,
        "LegalComplianceConcern": False,
        "HumanInTheLoopRequired": True,
        "NextStep": "Document current license tiers and access process. Create standard work for Copilot enablement. Identify IT contact owner.",
        "ScheduleHealth": "Not Started",
        "ValueScore": 4,
        "EffortScore": 3,
        "RiskScore": 3,
        "ReadinessScore": 3,
        "SignalScore": 4,
        "SuggestedBusinessOwnerText": "Baker, Youssef F",
        "SuggestedTechnicalOwnerText": "Gonzalez Medina, Oscar A",
        "SuggestedSMEChampionText": "Gonzalez Medina, Oscar A",
        "EvidenceSummary": "Oscar asked about users not getting access to the compiled license. Jesse added that non-technical users need a clearer onboarding path.",
        "SourceSpeaker": "Gonzalez Medina, Oscar A",
        "SourceTimestamp": "12:55",
        "ConfidenceLevel": "High",
    },
    {
        "Title": "Command-Line / Technical Barrier Onboarding Guide",
        "ProblemPainPoint": "Users unfamiliar with command-line tools face a barrier to AI tool adoption. No beginner-friendly onboarding path currently exists.",
        "RequestingTeam": "Cross Functional",
        "CurrentStatus": "(2) Needs Review",
        "Priority": "High",
        "OperatingBucket": "Crosss-Functional/Governance",
        "ProcessStage": "Governance/Intake",
        "UpstreamDownstreamImpact": "Downstream",
        "AIUseCaseType": "Classification",
        "PrimaryFunctionChoice": "Generate Content",
        "LevelOfAnalysis": "Level 1 - Categorization",
        "HumanReviewRequired": True,
        "AutomationRisk": "Low - Read Only/Summarize Only",
        "SignalStrength": "Isolated Example",
        "FrequencyOfPainPoint": "Occasional",
        "ManualEffortLevel": "Medium",
        "Repeatability": "Medium",
        "ScalabilityPotential": "Cross-Functional",
        "PrimaryTool": "Copilot",
        "PrimaryDataSource": "Meeting Transcript",
        "IntegrationNeeded": False,
        "DataSensitivity": "Internal",
        "GuardrailsNeeded": "Onboarding guide should be reviewed by L&D and IT before distribution.",
        "SecurityAccessConcern": False,
        "LegalComplianceConcern": False,
        "HumanInTheLoopRequired": True,
        "NextStep": "Draft a non-technical onboarding guide for AI tooling. Pilot with a team that has low CLI familiarity.",
        "ScheduleHealth": "Not Started",
        "ValueScore": 3,
        "EffortScore": 2,
        "RiskScore": 1,
        "ReadinessScore": 3,
        "SignalScore": 2,
        "SuggestedBusinessOwnerText": "",
        "SuggestedTechnicalOwnerText": "",
        "SuggestedSMEChampionText": "Horwitz, Jesse",
        "EvidenceSummary": "Jesse asked whether people uncomfortable using command line tools could hear about the tooling in a way that reduces friction.",
        "SourceSpeaker": "Horwitz, Jesse",
        "SourceTimestamp": "16:20",
        "ConfidenceLevel": "Medium",
    },
    {
        "Title": "Visual Installer Product Documentation Pipeline (AI-Assisted)",
        "ProblemPainPoint": "Product documentation for Visual Installer is manually written. Synthesizing how-to guides from raw content is time-consuming and inconsistent.",
        "RequestingTeam": "Product Management",
        "CurrentStatus": "(2) Needs Review",
        "Priority": "High",
        "OperatingBucket": "Inside/Pre-Sale",
        "ProcessStage": "Solution Development",
        "UpstreamDownstreamImpact": "Downstream",
        "AIUseCaseType": "Both",
        "PrimaryFunctionChoice": "Generate Content",
        "LevelOfAnalysis": "Leve 6 - Action/Automation",
        "HumanReviewRequired": True,
        "AutomationRisk": "Medium - Recommendations with human review",
        "SignalStrength": "Isolated Example",
        "FrequencyOfPainPoint": "Continuous",
        "ManualEffortLevel": "High",
        "Repeatability": "High",
        "ScalabilityPotential": "Function-Specific",
        "PrimaryTool": "Copilot",
        "PrimaryDataSource": "Meeting Transcript",
        "IntegrationNeeded": False,
        "DataSensitivity": "Internal",
        "GuardrailsNeeded": "AI-generated documentation must be reviewed by a PM or technical writer before publishing. Do not auto-publish.",
        "SecurityAccessConcern": False,
        "LegalComplianceConcern": False,
        "HumanInTheLoopRequired": True,
        "NextStep": "Document current pipeline. Define review/approval step. Assess reusability across other product lines.",
        "ScheduleHealth": "Not Started",
        "ValueScore": 5,
        "EffortScore": 3,
        "RiskScore": 2,
        "ReadinessScore": 4,
        "SignalScore": 3,
        "SuggestedBusinessOwnerText": "Hein, David M",
        "SuggestedTechnicalOwnerText": "Hein, David M",
        "SuggestedSMEChampionText": "Hein, David M",
        "EvidenceSummary": "David M Hein presented a product manager workflow using AI agents to organize and synthesize documentation into how-to guide format for Visual Installer.",
        "SourceSpeaker": "Hein, David M",
        "SourceTimestamp": "19:12",
        "ConfidenceLevel": "High",
    },
    {
        "Title": "AI-Assisted Content Organization & Coaching Workflow",
        "ProblemPainPoint": "Unstructured content must be manually organized into structured how-to guides, a repeated and time-consuming task for product managers.",
        "RequestingTeam": "Product Management",
        "CurrentStatus": "(2) Needs Review",
        "Priority": "High",
        "OperatingBucket": "Inside/Pre-Sale",
        "ProcessStage": "Solution Development",
        "UpstreamDownstreamImpact": "Downstream",
        "AIUseCaseType": "Classification",
        "PrimaryFunctionChoice": "Organize",
        "LevelOfAnalysis": "Level 2 - Descriptive Analysis",
        "HumanReviewRequired": True,
        "AutomationRisk": "Low - Read Only/Summarize Only",
        "SignalStrength": "Isolated Example",
        "FrequencyOfPainPoint": "Weekly",
        "ManualEffortLevel": "High",
        "Repeatability": "Very High",
        "ScalabilityPotential": "Function-Specific",
        "PrimaryTool": "Copilot",
        "PrimaryDataSource": "Meeting Transcript",
        "IntegrationNeeded": False,
        "DataSensitivity": "Internal",
        "GuardrailsNeeded": "Human review of structured output before use in official documentation.",
        "SecurityAccessConcern": False,
        "LegalComplianceConcern": False,
        "HumanInTheLoopRequired": True,
        "NextStep": "Capture current prompt/agent pattern. Package as a reusable skill. Add to skills repository.",
        "ScheduleHealth": "Not Started",
        "ValueScore": 4,
        "EffortScore": 2,
        "RiskScore": 1,
        "ReadinessScore": 4,
        "SignalScore": 3,
        "SuggestedBusinessOwnerText": "Hein, David M",
        "SuggestedTechnicalOwnerText": "",
        "SuggestedSMEChampionText": "Hein, David M",
        "EvidenceSummary": "The agent has been helping David coach how to organize content into structured how-to guides, replacing a previously manual synthesis process.",
        "SourceSpeaker": "Hein, David M",
        "SourceTimestamp": "33:07",
        "ConfidenceLevel": "High",
    },
    {
        "Title": "Content Accessibility & Consumption Format Standard",
        "ProblemPainPoint": "AI-generated content lacks a defined format standard for accessibility and downstream consumption, risking inconsistent delivery.",
        "RequestingTeam": "Cross Functional",
        "CurrentStatus": "(2) Needs Review",
        "Priority": "High",
        "OperatingBucket": "Crosss-Functional/Governance",
        "ProcessStage": "Governance/Intake",
        "UpstreamDownstreamImpact": "Downstream",
        "AIUseCaseType": "Classification",
        "PrimaryFunctionChoice": "Organize",
        "LevelOfAnalysis": "Level 1 - Categorization",
        "HumanReviewRequired": True,
        "AutomationRisk": "Low - Read Only/Summarize Only",
        "SignalStrength": "Isolated Example",
        "FrequencyOfPainPoint": "Occasional",
        "ManualEffortLevel": "Low",
        "Repeatability": "Medium",
        "ScalabilityPotential": "Cross-Functional",
        "PrimaryTool": "Copilot",
        "PrimaryDataSource": "Meeting Transcript",
        "IntegrationNeeded": False,
        "DataSensitivity": "Internal",
        "GuardrailsNeeded": "Format standards should be aligned with L&D and communications teams.",
        "SecurityAccessConcern": False,
        "LegalComplianceConcern": False,
        "HumanInTheLoopRequired": True,
        "NextStep": "Define content accessibility and format standards for AI-generated outputs. Circulate for working group review.",
        "ScheduleHealth": "Not Started",
        "ValueScore": 3,
        "EffortScore": 2,
        "RiskScore": 1,
        "ReadinessScore": 2,
        "SignalScore": 2,
        "SuggestedBusinessOwnerText": "",
        "SuggestedTechnicalOwnerText": "",
        "SuggestedSMEChampionText": "Hein, David M",
        "EvidenceSummary": "David noted that content should be made accessible to consume and identified capturing accessibility format requirements as a next step.",
        "SourceSpeaker": "Hein, David M",
        "SourceTimestamp": "36:37",
        "ConfidenceLevel": "Medium",
    },
    {
        "Title": "Skills / Prompts Repository Maintenance Model",
        "ProblemPainPoint": "The growing skills/prompts repository has no defined maintainer or sustainment model, creating a single-point-of-failure risk as adoption scales.",
        "RequestingTeam": "Cross Functional",
        "CurrentStatus": "(2) Needs Review",
        "Priority": "High",
        "OperatingBucket": "Crosss-Functional/Governance",
        "ProcessStage": "Governance/Intake",
        "UpstreamDownstreamImpact": "Cross-Functional",
        "AIUseCaseType": "Both",
        "PrimaryFunctionChoice": "Organize",
        "LevelOfAnalysis": "Level 1 - Categorization",
        "HumanReviewRequired": True,
        "AutomationRisk": "Low - Read Only/Summarize Only",
        "SignalStrength": "Repeated within One Team",
        "FrequencyOfPainPoint": "Continuous",
        "ManualEffortLevel": "Medium",
        "Repeatability": "High",
        "ScalabilityPotential": "Cross-Functional",
        "PrimaryTool": "VS Code",
        "PrimaryDataSource": "Meeting Transcript",
        "IntegrationNeeded": True,
        "DataSensitivity": "Internal",
        "GuardrailsNeeded": "Repo access controls should be reviewed. Skills should be reviewed before publishing to avoid propagating bad prompts.",
        "SecurityAccessConcern": False,
        "LegalComplianceConcern": False,
        "HumanInTheLoopRequired": True,
        "NextStep": "Define maintainer role and sustainment model for skills repo. Document contribution and review process.",
        "ScheduleHealth": "Not Started",
        "ValueScore": 4,
        "EffortScore": 2,
        "RiskScore": 2,
        "ReadinessScore": 3,
        "SignalScore": 3,
        "SuggestedBusinessOwnerText": "",
        "SuggestedTechnicalOwnerText": "Zaveruha, Ryan A",
        "SuggestedSMEChampionText": "Zaveruha, Ryan A",
        "EvidenceSummary": "Ryan discussed maintaining the skills repo in Azure. David agreed a clear maintainer and sustainment model is needed.",
        "SourceSpeaker": "Zaveruha, Ryan A",
        "SourceTimestamp": "40:35",
        "ConfidenceLevel": "High",
    },
    {
        "Title": "Knowledge Base Candidate Pipeline — Release Notes & VAS Standard Work",
        "ProblemPainPoint": "KB candidates identified in working group meetings have no structured intake pipeline to move from discussion to published KB article.",
        "RequestingTeam": "Cross Functional",
        "CurrentStatus": "(2) Needs Review",
        "Priority": "High",
        "OperatingBucket": "Crosss-Functional/Governance",
        "ProcessStage": "Governance/Intake",
        "UpstreamDownstreamImpact": "Downstream",
        "AIUseCaseType": "Both",
        "PrimaryFunctionChoice": "Create Records",
        "LevelOfAnalysis": "Leve 6 - Action/Automation",
        "HumanReviewRequired": True,
        "AutomationRisk": "High - Creates or updates work items",
        "SignalStrength": "Cross-Functional Pattern",
        "FrequencyOfPainPoint": "Weekly",
        "ManualEffortLevel": "High",
        "Repeatability": "Very High",
        "ScalabilityPotential": "Cross-Functional",
        "PrimaryTool": "Sharepoint",
        "PrimaryDataSource": "Meeting Transcript",
        "IntegrationNeeded": True,
        "DataSensitivity": "Internal",
        "GuardrailsNeeded": "KB articles must be reviewed and approved by a subject matter expert before publishing. Do not auto-publish.",
        "SecurityAccessConcern": False,
        "LegalComplianceConcern": False,
        "HumanInTheLoopRequired": True,
        "NextStep": "Define KB candidate intake process. Assign owners for release notes and VAS standard work KB items. Set target publish dates.",
        "ScheduleHealth": "Not Started",
        "ValueScore": 5,
        "EffortScore": 3,
        "RiskScore": 3,
        "ReadinessScore": 3,
        "SignalScore": 5,
        "SuggestedBusinessOwnerText": "High, David K",
        "SuggestedTechnicalOwnerText": "",
        "SuggestedSMEChampionText": "High, David K",
        "EvidenceSummary": "David K High stated there are two KB candidates in motion — release notes documentation and VAS standard work — being progressed through the KB pipeline.",
        "SourceSpeaker": "High, David K",
        "SourceTimestamp": "44:48",
        "ConfidenceLevel": "High",
    },
]
